In [2]:
def total(*args):
    print(type(args))
    print(sum(args))

total(1,2,4,5,3)

<class 'tuple'>
15


## Numpy start

In [10]:
list1 = [1,2,3,4,5]
list2 = [1,3,5,7,4]

In [8]:
list1,list2

([1, 2, 3, 4, 5], [1, 3, 5, 7, 4])

In [11]:
list1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [17]:
list3 = []
for i in range(len(list1)):
    list3.append(list1[i] * list2[i])

In [18]:
list3

[1, 6, 15, 28, 20]

In [19]:
import numpy as np

In [21]:
n1 = np.array(list1)
n2 = np.array(list2)

In [22]:
n2 * n1

array([ 1,  6, 15, 28, 20])

In [35]:
new = np.array([1,2,3,4,5,6,7,8])

In [31]:
new

array(['1', '2', '3', '4', '5', '6', '7', '8', 'c'], dtype='<U21')

In [32]:
type(new)

numpy.ndarray

In [33]:
new.dtype

dtype('<U21')

In [34]:
new.shape

(9,)

In [38]:
new_resl = np.append(new,['c'])
new_resl,type(new_resl)

(array(['1', '2', '3', '4', '5', '6', '7', '8', 'c'], dtype='<U21'),
 numpy.ndarray)

In [40]:
new.ndim

1

In [41]:
new.size

8

In [44]:
new_arrange = np.arange(0,100,5)
new_arrange

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [51]:
new_empty = np.empty(4)
new_empty

array([0., 0., 0., 0.])

In [55]:
new_linspace = np.linspace(0,10,num=15)
new_linspace

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [54]:
new_zeros = np.zeros(5)
new_zeros

array([0., 0., 0., 0., 0.])

In [56]:
matrix = np.array([[1,2,3,4],[3,4,4,5],[4,3,1,2]])
matrix

array([[1, 2, 3, 4],
       [3, 4, 4, 5],
       [4, 3, 1, 2]])

In [58]:
new,np.sum(new),np.mean(new),new**3

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 np.int64(36),
 np.float64(4.5),
 array([  1,   8,  27,  64, 125, 216, 343, 512]))

In [61]:
new_random = np.random.randn(12)
new_random




array([-0.62615208,  0.97939631,  1.47769432,  0.50504953,  0.84302048,
       -0.89051509, -1.72854161,  0.27617946, -0.33255962, -1.66501176,
        2.15991098,  1.12384466])

In [64]:
new_random = np.random.randint(1,15,(3,4))
new_random

array([[ 5, 14, 12,  8],
       [ 7,  8,  9,  4],
       [11, 13, 14, 10]])

In [67]:
new_normal = np.random.normal(3,4,5)
new_normal


array([ 1.52859549,  8.07725299,  8.81113759,  4.83537732, -1.05473835])

In [69]:
matrix_identity = np.eye(4)
matrix_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
matrix_diag = np.diag([1,4,5,6,6])
matrix_diag

array([[1, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 6]])

In [75]:
matrix_full = np.full([3,4],5)
matrix_full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [77]:
new_transpose = np.transpose(new_random)
new_transpose

array([[ 5,  7, 11],
       [14,  8, 13],
       [12,  9, 14],
       [ 8,  4, 10]])

In [91]:
try_reshape = np.arange(1,10)
try_reshape

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
m3x3 = try_reshape.reshape(3,3)
m3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
import numpy.linalg as linalg


In [97]:
m3x3_inv = linalg.inv(m3x3)
m3x3_inv

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [103]:
mat2d = np.arange(25).reshape(5,5)
mat2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
flaten_2d = mat2d.flatten()
flaten_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [111]:
ravel_2d = mat2d.ravel()
ravel_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [112]:
print(flaten_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [117]:

# Modifying a Ravel array updates the parent matrix
ravel_2d[0] = 99
print(mat2d[0, 0]) 
print(mat2d)
print(ravel_2d) 


# Output: 99 (The original matrix changed!)

# Modifying a Flatten array protects the parent matrix
flaten_2d[1] = 88
print(mat2d[0, 1]) 
# Output: 2 (The original matrix is unchanged)
print(mat2d)
print(flaten_2d) 

99
[[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
1
[[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0 88  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
