In [1]:
import numpy as np
import pandas as pd

In [2]:
#problem 1

array_np = np.array([11,22,33,44,55,66])
print(array_np)

[11 22 33 44 55 66]


In [3]:
# problem 3

def temp_analysis(incoming_array):
    temp_array = np.array(incoming_array)
    days = ['Sun', 'Mon', 'Tues', 'Wed', 'Thrus', 'Fir', 'Sat']
    print(f"Average temperature: {np.average(temp_array)}")
    print(f"Maximum Temperature: {np.max(temp_array)}")
    print(f"Minimum temperatur: {np.min(temp_array)}")
    print(f"Day with max temperature:  Day {days[np.argmax(temp_array)]}") 
    # argmax return the index of the element
    print(f"Days with more than average temp: ")
    avg = np.average(temp_array)
    for i in range(0,temp_array.size):
        if temp_array[i]  > avg:
            print(f"{temp_array[i]}")
    
    

In [4]:
temp_list = [32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0]
temp_analysis(temp_list)


Average temperature: 31.842857142857145
Maximum Temperature: 34.5
Minimum temperatur: 29.8
Day with max temperature:  Day Thrus
Days with more than average temp: 
32.5
33.1
34.5


In [39]:
#problem 4

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Matrix:")
matrix

Matrix:


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
print("First row:")
matrix[0, :]

First row:


array([1, 2, 3, 4])

In [41]:
print("First column:")
matrix[:, 0]


First column:


array([1, 5, 9])

In [42]:
print("Last column:")
matrix[:, -1]

Last column:


array([ 4,  8, 12])

In [43]:
print("Every alternate element:")
mat_flat = matrix.flatten()
mat_flat[::2]

Every alternate element:


array([ 1,  3,  5,  7,  9, 11])

In [44]:
print("Shape:")
matrix.shape

Shape:


(3, 4)

In [45]:
print("Number of dimensions:")
matrix.ndim

Number of dimensions:


2

In [46]:
print("Total number of elements:")
matrix.size

Total number of elements:


12

In [47]:
#problem 4
og_array = np.random.randint(1, 51,50)

print("Original array:")
og_array

Original array:


array([39, 27,  2, 27, 31, 33, 22, 43, 17, 20, 24, 25, 23, 21, 46, 50, 11,
       33, 30, 10, 22, 11, 18, 17, 40, 48, 13, 17, 39, 31, 38, 28, 49,  4,
       35, 45, 32, 15, 36,  4, 44,  9, 41, 27, 19, 36, 14,  5, 14, 11])

In [48]:

even_array= og_array[og_array % 2 == 0]

odd_array = og_array[og_array % 2 != 0]

print("\nEven numbers:")
even_array



Even numbers:


array([ 2, 22, 20, 24, 46, 50, 30, 10, 22, 18, 40, 48, 38, 28,  4, 32, 36,
        4, 44, 36, 14, 14])

In [49]:
print("\nOdd numbers:")
odd_array


Odd numbers:


array([39, 27, 27, 31, 33, 43, 17, 25, 23, 21, 11, 33, 11, 17, 13, 17, 39,
       31, 49, 35, 45, 15,  9, 41, 27, 19,  5, 11])

In [15]:
#problem 5

In [50]:
og_array = np.random.randint(1, 101, 30)

print("Generated array:")
og_array

Generated array:


array([64, 43, 11, 27, 87, 18, 29, 76, 94, 42, 24, 64, 34, 18, 70, 29, 53,
       85, 89, 87, 72, 26, 51, 66, 86,  3, 73, 52, 38, 59])

In [17]:
above_50 = og_array[og_array > 50]
print(f"Values greater than 50: {above_50}")


print(f"Values between 25 and 75: {og_array[(og_array >= 25) & (og_array <= 75)]}")


print(f"Count of values greater than 50: { np.sum(og_array > 50)}")


print(f"Average of values greater than 50: {np.mean(above_50)}")


Values greater than 50: [71 54 79 78 91 70 77 93 59 71 65 64 63 76 64 58 84 85 98]
Values between 25 and 75: [71 45 33 54 70 40 27 43 59 71 27 65 64 63 41 64 58]
Count of values greater than 50: 19
Average of values greater than 50: 73.6842105263158


In [18]:
#problem 6

In [19]:
# i dont know should we use pandas as well
marks = np.array([
    [78, 82, 91],
    [65, 74, 80],
    [92, 88, 95],
    [56, 69, 72],
    [84, 90, 87]
])



In [20]:
print(f"Student marks: {marks}")

Student marks: [[78 82 91]
 [65 74 80]
 [92 88 95]
 [56 69 72]
 [84 90 87]]


In [23]:
student_avg = []

print("Average marks of each student:")
for student in marks:
    avg = np.mean(student)
    student_avg.append(avg)
    print(avg)

subject_avg = []

print("\nAverage marks in each subject:")
for i in range(marks.shape[1]):
    avg = np.mean(marks[:, i])
    subject_avg.append(avg)
    print(avg)

Average marks of each student:
83.66666666666667
73.0
91.66666666666667
65.66666666666667
87.0

Average marks in each subject:
75.0
80.6
85.0


In [24]:
print(f"Highest mark: {np.max(marks)}")

print(f"Lowest mark: {np.min(marks)}")

highest_student = np.argmax(student_avg)
print(f"Student with highest average: Student {highest_student + 1}")

subjects = ["Mathematics", "Physics", "Programming"]
highest_subject = np.argmax(subject_avg)

print(f"Subject with highest average: {subjects[highest_subject]}")

Highest mark: 95
Lowest mark: 56
Student with highest average: Student 3
Subject with highest average: Programming


In [25]:
## just trying pandas (ignore)

In [35]:
marks = np.array([
    [78, 82, 91],
    [65, 74, 80],
    [92, 88, 95],
    [56, 69, 72],
    [84, 90, 87]
])

subjects = ["Mathematics", "Physics", "Programming"]
students = ["Student 1", "Student 2", "Student 3", "Student 4", "Student 5"]

df = pd.DataFrame(
    marks,
    columns=subjects,
)

df["Student"] = students
df.set_index("Student", inplace=True)

print("Student marks:")
print(df)

print("Average marks of each student:")
student_avg = []

for student in df.index:
    avg = df.loc[student].mean()
    student_avg.append(avg)
    print(f"{student}: {avg}")


Student marks:
           Mathematics  Physics  Programming
Student                                     
Student 1           78       82           91
Student 2           65       74           80
Student 3           92       88           95
Student 4           56       69           72
Student 5           84       90           87
Average marks of each student:
Student 1: 83.66666666666667
Student 2: 73.0
Student 3: 91.66666666666667
Student 4: 65.66666666666667
Student 5: 87.0


In [36]:

print("Average marks in each subject:")
subject_avg = []

for subject in df.columns:
    avg = df[subject].mean()
    subject_avg.append(avg)
    print(f"{subject}: {avg}")


Average marks in each subject:
Mathematics: 75.0
Physics: 80.6
Programming: 85.0


In [37]:

print(f"Highest mark: {df.max().max()}")
print(f"Lowest mark: {df.min().min()}")

highest_student = df.mean(axis=1).idxmax()
print(f"Student with highest average: {highest_student}")

highest_subject = df.mean(axis=0).idxmax()
print(f"Subject with highest average: {highest_subject}")

Highest mark: 95
Lowest mark: 56
Student with highest average: Student 3
Subject with highest average: Programming


In [52]:
# problem 7

matrix_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

In [53]:
matrix_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
matrix_2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [55]:

matrix_1 + matrix_2


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [56]:

print("Subtraction:")
matrix_1 - matrix_2


Subtraction:


array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [57]:

print("multiplication:")
matrix_1 * matrix_2


multiplication:


array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [59]:
print("Matrix multiplication 2.O:")
matrix_1 @ matrix_2

## or np.dot(matrix_1, matrix_2

Matrix multiplication 2.O:


array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

Element wise multiplication multiplies elements of the two matrices... 
But matrix multiplication calculates each element using the dot product of a row from the first matrix and a column from the second matrix...

In [61]:
# problem 8

def data_transformation(incoming_array):

    data = np.array(incoming_array)

    squared = np.square(data)
    square_root = np.sqrt(data)
    exponential = np.exp(data)

    print(f"Original data: {data}")

    print(f"\nSquare of measurements: {squared}")
    print(f"Mean of squared data: {np.mean(squared)}")

    print(f"\nSquare root of measurements: {square_root}")
    print(f"Mean of square root data: {np.mean(square_root)}")

    print(f"\nExponential of measurements: {exponential}")
    print(f"Mean of exponential data: {np.mean(exponential)}")

In [62]:

measurements = [2, 4, 6, 8, 10, 12]

data_transformation(measurements)

Original data: [ 2  4  6  8 10 12]

Square of measurements: [  4  16  36  64 100 144]
Mean of squared data: 60.666666666666664

Square root of measurements: [1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]
Mean of square root data: 2.5530849508680995

Exponential of measurements: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]
Mean of exponential data: 31371.271866746192


In [63]:
# problem 9

data = np.arange(1, 25)

print("Original array:")
data

Original array:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [64]:
array_4x6 = data.reshape(4, 6)
array_4x6, print(f"Shape: {array_4x6.shape}")

Shape: (4, 6)


(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 None)

In [66]:

array_6x4 = data.reshape(6, 4)
print("\n6 x 4 array:")
print(array_6x4)
print(f"Shape: {array_6x4.shape}")


6 x 4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)


In [68]:

array_2x3x4 = data.reshape(2, 3, 4)
print("\n2 x 3 x 4 array:")
print(array_2x3x4)
print(f"Shape: {array_2x3x4.shape}")


2 x 3 x 4 array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [69]:
one_dimensional = array_4x6.flatten()
print("\n4 x 6 array converted back to 1-D:")
print(one_dimensional)
print(f"Shape: {one_dimensional.shape}")


4 x 6 array converted back to 1-D:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)


In [70]:
# problem 10
experiment_1 = np.array([10, 20, 30, 40, 50])
experiment_2 = np.array([15, 25, 35, 45, 55])

print("Experiment 1:")
print(experiment_1)

print("\nExperiment 2:")
print(experiment_2)

Experiment 1:
[10 20 30 40 50]

Experiment 2:
[15 25 35 45 55]


In [73]:
# Single 1-D array
combined_1d = np.concatenate((experiment_1, experiment_2))

print("\nCombined 1-D array:")
print(combined_1d)
print(f"Shape: {combined_1d.shape}")


Combined 1-D array:
[10 20 30 40 50 15 25 35 45 55]
Shape: (10,)


In [74]:
# Experiments as separate rows
combined_rows = np.vstack((experiment_1, experiment_2))

print("\nExperiments as separate rows:")
print(combined_rows)
print(f"Shape: {combined_rows.shape}")


Experiments as separate rows:
[[10 20 30 40 50]
 [15 25 35 45 55]]
Shape: (2, 5)


In [76]:
# Experiments as separate columns
combined_columns = np.column_stack((experiment_1, experiment_2))

print("\nExperiments as separate columns:")
print(combined_columns)
print(f"Shape: {combined_columns.shape}")


Experiments as separate columns:
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
Shape: (5, 2)


In [82]:
# problem 11

measurements = np.array([10, 12, 15, 200, 13, 11, 14, 250, 12, 15])

print("Original measurements:")
measurements

Original measurements:


array([ 10,  12,  15, 200,  13,  11,  14, 250,  12,  15])

In [83]:
invalid = measurements[measurements > 100]
invalid

array([200, 250])

In [84]:
valid = measurements[measurements <= 100]
valid


array([10, 12, 15, 13, 11, 14, 12, 15])

In [88]:
print(f"min: {np.min(image)}, min valid: {np.min(valid)}, max valid: { np.max(valid)} ")

min: 0, min valid: 10, max valid: 15 


In [89]:
# problem 12

image = np.array([
    [0, 0, 0, 255, 255],
    [0, 0, 128, 255, 255],
    [0, 128, 128, 128, 255],
    [0, 0, 128, 0, 0],
    [255, 0, 0, 0, 255]
])

image


array([[  0,   0,   0, 255, 255],
       [  0,   0, 128, 255, 255],
       [  0, 128, 128, 128, 255],
       [  0,   0, 128,   0,   0],
       [255,   0,   0,   0, 255]])

In [92]:
print(f"Minimum pixel intensity: {np.min(image)}")
print(f"Maximum pixel intensity: {np.max(image)}")
print(f"Mean pixel intensity: {np.mean(image)}")

Minimum pixel intensity: 0
Maximum pixel intensity: 255
Mean pixel intensity: 97.0


In [94]:

print(f"Number of pixels with intensity greater than 100: {np.sum(image > 100)}")

print(f"Pixels with intensity equal to 255: {image[image == 255]}")

Number of pixels with intensity greater than 100: 12
Pixels with intensity equal to 255: [255 255 255 255 255 255 255]


In [95]:
above_100 = image[image > 100]
above_100

array([255, 255, 128, 255, 255, 128, 128, 128, 255, 128, 255, 255])

In [96]:
# problem 13

experiment_A = np.array([12, 15, 14, 18, 20, 17, 16])
experiment_B = np.array([10, 13, 15, 16, 19, 21, 18])

experiment_A

array([12, 15, 14, 18, 20, 17, 16])

In [98]:
experiment_B

array([10, 13, 15, 16, 19, 21, 18])

In [100]:
print(f"\nMean of Experiment A: {np.mean(experiment_A)}")
print(f"Mean of Experiment B: {np.mean(experiment_B)}")


Mean of Experiment A: 16.0
Mean of Experiment B: 16.0


In [102]:

print(f"\nStandard deviation of Experiment A: {np.std(experiment_A)}")
print(f"Standard deviation of Experiment B: {np.std(experiment_B)}")


Standard deviation of Experiment A: 2.449489742783178
Standard deviation of Experiment B: 3.4641016151377544


In [104]:
print(f"\nMaximum of Experiment A: {np.max(experiment_A)}")
print(f"Maximum of Experiment B: {np.max(experiment_B)}")

print(f"\nMinimum of Experiment A: {np.min(experiment_A)}")
print(f"Minimum of Experiment B: {np.min(experiment_B)}")


Maximum of Experiment A: 20
Maximum of Experiment B: 21

Minimum of Experiment A: 12
Minimum of Experiment B: 10


In [105]:
difference = experiment_A - experiment_B
print(f"\nDifference between experiments: {difference}")


Difference between experiments: [ 2  2 -1  2  1 -4 -2]


In [106]:
if np.std(experiment_A) > np.std(experiment_B):
    print("Experiment A shows greater variation.")
else:
    print("Experiment B shows greater variation.")

Experiment B shows greater variation.


In [107]:
# problem 14

def analyze_data(data):

    print("Dataset:")
    print(data)

    print(f"\nShape: {data.shape}")
    print(f"Dimensions: {data.ndim}")

    print("\nMean of each variable:")
    for i in range(data.shape[1]):
        print(np.mean(data[:, i]))

    print("\nMean of each experiment:")
    for i in range(data.shape[0]):
        print(np.mean(data[i]))

    print(f"\nMaximum value: {np.max(data)}")
    print(f"Minimum value: {np.min(data)}")

    overall_mean = np.mean(data)
    print(f"\nOverall mean: {overall_mean}")
    print(f"Values above overall mean: {data[data > overall_mean]}")

In [108]:
def reshape_data(data):

    reshaped = data.reshape(5, 10)

    print("\nReshaped data:")
    print(reshaped)

    flattened = reshaped.flatten()

    print("\nFlattened data:")
    print(flattened)


In [109]:
data = np.random.randint(1, 101, (10, 5))

analyze_data(data)
reshape_data(data)

Dataset:
[[56 25 50 83 24]
 [87 63 96 70 44]
 [29 28 15 29 39]
 [90 72 68 49 39]
 [38 78 60 88 57]
 [32 78  6 37 49]
 [43 83 91 71 57]
 [17  5 29 94 44]
 [63 59 30 68 86]
 [86 84 99 64 43]]

Shape: (10, 5)
Dimensions: 2

Mean of each variable:
54.1
57.5
54.4
65.3
48.2

Mean of each experiment:
47.6
72.0
28.0
63.6
64.2
40.4
69.0
37.8
61.2
75.2

Maximum value: 99
Minimum value: 5

Overall mean: 55.9
Values above overall mean: [56 83 87 63 96 70 90 72 68 78 60 88 57 78 83 91 71 57 94 63 59 68 86 86
 84 99 64]

Reshaped data:
[[56 25 50 83 24 87 63 96 70 44]
 [29 28 15 29 39 90 72 68 49 39]
 [38 78 60 88 57 32 78  6 37 49]
 [43 83 91 71 57 17  5 29 94 44]
 [63 59 30 68 86 86 84 99 64 43]]

Flattened data:
[56 25 50 83 24 87 63 96 70 44 29 28 15 29 39 90 72 68 49 39 38 78 60 88
 57 32 78  6 37 49 43 83 91 71 57 17  5 29 94 44 63 59 30 68 86 86 84 99
 64 43]


In [110]:
#problem 15
subjects = ["Mathematics", "Physics", "Programming", "Statistics"]

In [111]:
marks = np.random.randint(0, 101, (10, 4))

marks

array([[98, 29, 94, 68],
       [92, 24,  7, 61],
       [19, 27, 87, 37],
       [20, 14, 60, 21],
       [93, 65, 96, 87],
       [86, 32, 56, 11],
       [72, 23, 12, 68],
       [82, 43, 44, 92],
       [56, 86, 74, 39],
       [85, 87, 96, 21]])

In [112]:
# every student
student_avg = np.mean(marks, axis=1)

student_avg

array([72.25, 46.  , 42.5 , 28.75, 85.25, 46.25, 43.75, 65.25, 63.75,
       72.25])

In [113]:
# every subject
subject_avg = np.mean(marks, axis=0)

subject_avg

array([70.3, 43. , 62.6, 50.5])

In [114]:
highest_student = np.argmax(student_avg)

highest_student + 1

np.int64(5)

In [116]:
lowest_student = np.argmin(student_avg)

lowest_student + 1

np.int64(4)

In [117]:
lowest_student = np.argmin(student_avg)

lowest_student + 1

np.int64(4)

In [118]:
lowest_mark = np.min(marks)

lowest_mark

np.int64(7)

In [119]:
students_above_75 = np.sum(student_avg > 75)

students_above_75

np.int64(1)

In [120]:
students_above_75 = np.sum(student_avg > 75)

students_above_75

np.int64(1)

In [121]:
marks_above_90 = marks[marks > 90]

marks_above_90

array([98, 94, 92, 93, 96, 92, 96])

In [122]:
grades = []

for avg in student_avg:
    if avg >= 90:
        grade = "A+"
    elif avg >= 80:
        grade = "A"
    elif avg >= 70:
        grade = "B"
    elif avg >= 60:
        grade = "C"
    elif avg >= 50:
        grade = "D"
    else:
        grade = "F"

    grades.append(grade)

grades

['B', 'F', 'F', 'F', 'A', 'F', 'F', 'C', 'C', 'B']

In [123]:
grades = []

for avg in student_avg:
    if avg >= 90:
        grade = "A+"
    elif avg >= 80:
        grade = "A"
    elif avg >= 70:
        grade = "B"
    elif avg >= 60:
        grade = "C"
    elif avg >= 50:
        grade = "D"
    else:
        grade = "F"

    grades.append(grade)

grades

['B', 'F', 'F', 'F', 'A', 'F', 'F', 'C', 'C', 'B']

In [125]:
student_information = []

for i in range(10):
    student_information.append({
        "Student": f"Student {i + 1}",
        "Average": student_avg[i],
        "Grade": grades[i]
    })

student_information

[{'Student': 'Student 1', 'Average': np.float64(72.25), 'Grade': 'B'},
 {'Student': 'Student 2', 'Average': np.float64(46.0), 'Grade': 'F'},
 {'Student': 'Student 3', 'Average': np.float64(42.5), 'Grade': 'F'},
 {'Student': 'Student 4', 'Average': np.float64(28.75), 'Grade': 'F'},
 {'Student': 'Student 5', 'Average': np.float64(85.25), 'Grade': 'A'},
 {'Student': 'Student 6', 'Average': np.float64(46.25), 'Grade': 'F'},
 {'Student': 'Student 7', 'Average': np.float64(43.75), 'Grade': 'F'},
 {'Student': 'Student 8', 'Average': np.float64(65.25), 'Grade': 'C'},
 {'Student': 'Student 9', 'Average': np.float64(63.75), 'Grade': 'C'},
 {'Student': 'Student 10', 'Average': np.float64(72.25), 'Grade': 'B'}]

In [126]:
df = pd.DataFrame(student_information)

df

,Student,Average,Grade
0,Student 1,72.25,B
1,Student 2,46.00,F
2,Student 3,42.50,F
3,Student 4,28.75,F
4,Student 5,85.25,A
5,Student 6,46.25,F
6,Student 7,43.75,F
7,Student 8,65.25,C
8,Student 9,63.75,C
9,Student 10,72.25,B
