In [2]:
#Problem 1. Make
#Make a numpy array and print it

import numpy as np
arr = np.array([3,4,5])
print(arr)

[3 4 5]


In [3]:
#Problem 2. Temperature Analysis

arr = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])

#print(arr)
sum = 0
#
for i in arr:
    sum += i
#print (sum)
def avg(arr):
    average = sum/arr.size
    return average

print("Average:",avg(arr))   
print("Maximum Temperature:", np.max(arr))
print("Minimum Temperature:", np.min(arr))
print("Day with maximum temperature:", np.argmax(arr))

average = avg(arr)
for i in arr:
    if i > average:        
        print("Temperature greater then average:",i)

Average: 31.842857142857145
Maximum Temperature: 34.5
Minimum Temperature: 29.8
Day with maximum temperature: 4
Temperature greater then average: 32.5
Temperature greater then average: 33.1
Temperature greater then average: 34.5


In [4]:
#Problem 3. Working with a Matrix

matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]])
print(matrix)
print("First row:",matrix[0])
print("Last row:", matrix[-1])
print("First Column:", matrix[:,0])
print("Last Column:", matrix[:,-1])
print("Middle Section:", matrix[0:2, 1:3]) #[rows, columns]
print("Every alternate element:", matrix[0:3, 0:4:2])
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
First Column: [1 5 9]
Last Column: [ 4  8 12]
Middle Section: [[2 3]
 [6 7]]
Every alternate element: [[ 1  3]
 [ 5  7]
 [ 9 11]]
Shape: (3, 4)
Dimensions: 2
Size: 12


In [5]:
#Problem 4. Even and Odd Numbers

arr = np.random.randint(1,50, size = 6)
print(arr)

arreven = []
arrodd = []

for i in arr:
    if i % 2 == 0:
        arreven.append(int(i))
    else:
        arrodd.append(int(i))
print(arreven)
print(arrodd)

[ 5  3 42 29 14 48]
[42, 14, 48]
[5, 3, 29]


In [8]:
#Problem 5. Numbers Above a Threshold

genarr = np.random.randint(1,101, size = 30)
arr50 = []
arr2550 = []
add = 0
cnt = 0
print("Array:", genarr)

for i in genarr:
    if i > 50:
        arr50.append(int(i))
        add += i
        cnt += 1
    elif i>25 & i<50:
        arr2550.append(int(i))
   
print("Numbers greater than 50:",arr50)
print("Numbers greater than 25 and smller than 50:",arr2550)
print("Count of numbers greater than 50:",cnt)
print("Average:", add/cnt)

Array: [68 83 32 94  8 22 88  8 69 13 63 79 89 12 75 30 29 85 80 11 35 15 34 96
  7 77 43 91 65 54]
Numbers greater than 50: [68, 83, 94, 88, 69, 63, 79, 89, 75, 85, 80, 96, 77, 91, 65, 54]
Numbers greater than 25 and smller than 50: [32, 22, 13, 12, 30, 29, 11, 35, 15, 34, 7, 43]
Count of numbers greater than 50: 16
Average: 78.5


In [9]:
#Problem 6. Student Performance Matrix

marks = np.array([
    [78, 82, 91],   # Student 1
    [65, 74, 80],   # Student 2
    [92, 88, 95],   # Student 3
    [56, 69, 72],   # Student 4
    [84, 90, 87]    # Student 5
])

student_avg = np.mean(marks, axis=1)
print("Average marks of each student:", student_avg)

subject_avg = np.mean(marks, axis=0)
print("Average marks of each subject:", subject_avg)

# Highest mark in entire dataset
print("Highest mark:", np.max(marks))
print("Lowest mark:", np.min(marks))
highest_student = np.argmax(student_avg)
print("Student with highest average: Student", highest_student + 1)
highest_subject = np.argmax(subject_avg)
subjects = ["Mathematics", "Physics", "Programming"]
print("Subject with highest average:", subjects[highest_subject])

Average marks of each student: [83.66666667 73.         91.66666667 65.66666667 87.        ]
Average marks of each subject: [75.  80.6 85. ]
Highest mark: 95
Lowest mark: 56
Student with highest average: Student 3
Subject with highest average: Programming


In [10]:
#Problem 7Matrix Operations
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
print("Addition:")
print(A + B)

print("Subtraction:")
print(A - B)

print("Element-wise multiplication:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [11]:
#Problem 8. Scientific Data Transformation

import numpy as np

def calculate(arr):
    square = arr ** 2
    square_root = np.sqrt(arr)
    exponential = np.exp(arr)

    print("Square:", square)
    print("Square root:", square_root)
    print("Exponential:", exponential)

    print("Mean of square:", np.mean(square))
    print("Mean of square root:", np.mean(square_root))
    print("Mean of exponential:", np.mean(exponential))


arr = np.array([2, 4, 6, 8, 10, 12])

calculate(arr)

Square: [  4  16  36  64 100 144]
Square root: [1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]
Mean of square: 60.666666666666664
Mean of square root: 2.5530849508680995
Mean of exponential: 31371.271866746192


In [12]:
#Problem 9. Reshaping Experimental Data

arr = np.arange(1, 25)
a = arr.reshape(4, 6)
b = arr.reshape(6, 4)
c = arr.reshape(2, 3, 4)

print("4 × 6 array:")
print(a)
print("Shape:", a.shape)

print("\n6 × 4 array:")
print(b)
print("Shape:", b.shape)

print("\n2 × 3 × 4 array:")
print(c)
print("Shape:", c.shape)

one_d = a.flatten()

print("\n1D array:")
print(one_d)
print("Shape:", one_d.shape)

4 × 6 array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

6 × 4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)

2 × 3 × 4 array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)

1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)


In [13]:
#Problem 10. Data Combination

experiment_1 = np.array([10, 20, 30, 40, 50])
experiment_2 = np.array([15, 25, 35, 45, 55])

one_d = np.concatenate((experiment_1, experiment_2))

rows = np.vstack((experiment_1, experiment_2))

columns = np.column_stack((experiment_1, experiment_2))

print("1D array:")
print(one_d)
print("Shape:", one_d.shape)

print("\nExperiments as rows:")
print(rows)
print("Shape:", rows.shape)

print("\nExperiments as columns:")
print(columns)
print("Shape:", columns.shape)

1D array:
[10 20 30 40 50 15 25 35 45 55]
Shape: (10,)

Experiments as rows:
[[10 20 30 40 50]
 [15 25 35 45 55]]
Shape: (2, 5)

Experiments as columns:
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
Shape: (5, 2)


In [14]:
#Problem 11. Simple Data Cleaning

import numpy as np

arr = np.array([10, 12, 15, 200, 13, 11, 14, 250, 12, 15])
invalid = arr[arr > 100]
valid = arr[arr <= 100]

print("Invalid measurements:", invalid)
print("Valid measurements:", valid)
print("Mean:", np.mean(valid))
print("Minimum:", np.min(valid))
print("Maximum:", np.max(valid))

Invalid measurements: [200 250]
Valid measurements: [10 12 15 13 11 14 12 15]
Mean: 12.75
Minimum: 10
Maximum: 15


In [15]:
#Problem 12. Image-like Matrix

image = np.array([
    [0, 0, 0, 255, 255],
    [0, 0, 128, 255, 255],
    [0, 128, 128, 128, 255],
    [0, 0, 128, 0, 0],
    [255, 0, 0, 0, 255]
])

print("Minimum:", np.min(image))
print("Maximum:", np.max(image))
print("Mean:", np.mean(image))
print("Pixels > 100:", np.sum(image > 100))
print("Pixels equal to 255:", image[image == 255])

new_array = image[image > 100]
print("Pixels greater than 100:")
print(new_array)

Minimum: 0
Maximum: 255
Mean: 97.0
Pixels > 100: 12
Pixels equal to 255: [255 255 255 255 255 255 255]
Pixels greater than 100:
[255 255 128 255 255 128 128 128 255 128 255 255]


In [16]:
#Problem 13. Experiment Comparison

experiment_A = np.array([12, 15, 14, 18, 20, 17, 16])
experiment_B = np.array([10, 13, 15, 16, 19, 21, 18])
print("Mean of A:", np.mean(experiment_A))
print("Mean of B:", np.mean(experiment_B))

print("Standard deviation of A:", np.std(experiment_A))
print("Standard deviation of B:", np.std(experiment_B))

print("Maximum of A:", np.max(experiment_A))
print("Maximum of B:", np.max(experiment_B))

print("Minimum of A:", np.min(experiment_A))
print("Minimum of B:", np.min(experiment_B))

difference = experiment_A - experiment_B
print("Difference:", difference)

if np.std(experiment_A) > np.std(experiment_B):
    print("Experiment A shows greater variation")
else:
    print("Experiment B shows greater variation")

Mean of A: 16.0
Mean of B: 16.0
Standard deviation of A: 2.449489742783178
Standard deviation of B: 3.4641016151377544
Maximum of A: 20
Maximum of B: 21
Minimum of A: 12
Minimum of B: 10
Difference: [ 2  2 -1  2  1 -4 -2]
Experiment B shows greater variation


In [17]:
#Problem 14. Mini Data Analysis Challenge

def create_data():
    data = np.random.randint(1, 100, size=(10, 5))
    return data

def analyze_data(data):

    print("Dataset:")
    print(data)

    print("\nShape:", data.shape)
    print("Dimensions:", data.ndim)

    print("\nMean of each variable:")
    print(np.mean(data, axis=0))

    print("\nMean of each experiment:")
    print(np.mean(data, axis=1))

    print("\nMaximum:", np.max(data))
    print("Minimum:", np.min(data))

    overall_mean = np.mean(data)
    print("\nOverall mean:", overall_mean)
    print("Values above overall mean:")
    print(data[data > overall_mean])

    reshaped = data.reshape(5, 10)
    print("\nReshaped data (5 × 10):")
    print(reshaped)
    print("New shape:", reshaped.shape)

    flattened = reshaped.flatten()
    print("\nFlattened data:")
    print(flattened)
    print("Flattened shape:", flattened.shape)

data = create_data()
analyze_data(data)

Dataset:
[[ 4 41 43 72 29]
 [33 88 63 44  2]
 [58 45 97 39 81]
 [ 5 30 64 10 60]
 [52 66 61 78 71]
 [14 60  6 93 65]
 [74 53 33 87 40]
 [46 60 78 16 37]
 [ 9 88 98 46  2]
 [92 63 43 54 90]]

Shape: (10, 5)
Dimensions: 2

Mean of each variable:
[38.7 59.4 58.6 53.9 47.7]

Mean of each experiment:
[37.8 46.  64.  33.8 65.6 47.6 57.4 47.4 48.6 68.4]

Maximum: 98
Minimum: 2

Overall mean: 51.66
Values above overall mean:
[72 88 63 58 97 81 64 60 52 66 61 78 71 60 93 65 74 53 87 60 78 88 98 92
 63 54 90]

Reshaped data (5 × 10):
[[ 4 41 43 72 29 33 88 63 44  2]
 [58 45 97 39 81  5 30 64 10 60]
 [52 66 61 78 71 14 60  6 93 65]
 [74 53 33 87 40 46 60 78 16 37]
 [ 9 88 98 46  2 92 63 43 54 90]]
New shape: (5, 10)

Flattened data:
[ 4 41 43 72 29 33 88 63 44  2 58 45 97 39 81  5 30 64 10 60 52 66 61 78
 71 14 60  6 93 65 74 53 33 87 40 46 60 78 16 37  9 88 98 46  2 92 63 43
 54 90]
Flattened shape: (50,)


In [18]:
#Problem 15. Final Challenge: Student Performance Analysis

def generate_marks():
    return np.random.randint(0, 101, size=(10, 4))

def calculate_student_average(marks):
    return np.mean(marks, axis=1)

def calculate_subject_average(marks):
    return np.mean(marks, axis=0)

def get_grade(average):
    if average >= 90:
        return "A+"
    elif average >= 80:
        return "A"
    elif average >= 70:
        return "B"
    elif average >= 60:
        return "C"
    elif average >= 50:
        return "D"
    else:
        return "F"

marks = generate_marks()

student_avg = calculate_student_average(marks)
subject_avg = calculate_subject_average(marks)

highest_student = np.argmax(student_avg)
lowest_student = np.argmin(student_avg)

highest_mark = np.max(marks)
lowest_mark = np.min(marks)
students_above_75 = np.sum(student_avg > 75)
marks_above_90 = marks[marks > 90]

students = []

for i in range(10):
    student = {
        "Student": i + 1,
        "Marks": marks[i],
        "Average": student_avg[i],
        "Grade": get_grade(student_avg[i])
    }

    students.append(student)

print("STUDENT PERFORMANCE ANALYSIS")

print("\nMarks:")
print(marks)

print("\nAverage mark of each student:")
for i in range(10):
    print(f"Student {i + 1}: {student_avg[i]:.2f}")

print("\nAverage mark of each subject:")
for i in range(4):
    print(f"Subject {i + 1}: {subject_avg[i]:.2f}")

print("\nStudent with highest average:")
print(f"Student {highest_student + 1} ({student_avg[highest_student]:.2f})")

print("\nStudent with lowest average:")
print(f"Student {lowest_student + 1} ({student_avg[lowest_student]:.2f})")

print("\nHighest mark in dataset:", highest_mark)
print("Lowest mark in dataset:", lowest_mark)

print("\nNumber of students with average above 75:",
      students_above_75)

print("\nAll marks greater than 90:")
print(marks_above_90)

print("\nStudent Grades:")
for student in students:
    print(
        f"Student {student['Student']}: "
        f"Average = {student['Average']:.2f}, "
        f"Grade = {student['Grade']}"
    )

STUDENT PERFORMANCE ANALYSIS

Marks:
[[25 68 26 83]
 [59 64 50 66]
 [69  1 95 46]
 [67 57 17 38]
 [93 90  9 71]
 [64 63 68 85]
 [52 25 15 93]
 [29 69 58 83]
 [42 72 82  6]
 [51 25 16  0]]

Average mark of each student:
Student 1: 50.50
Student 2: 59.75
Student 3: 52.75
Student 4: 44.75
Student 5: 65.75
Student 6: 70.00
Student 7: 46.25
Student 8: 59.75
Student 9: 50.50
Student 10: 23.00

Average mark of each subject:
Subject 1: 55.10
Subject 2: 53.40
Subject 3: 43.60
Subject 4: 57.10

Student with highest average:
Student 6 (70.00)

Student with lowest average:
Student 10 (23.00)

Highest mark in dataset: 95
Lowest mark in dataset: 0

Number of students with average above 75: 0

All marks greater than 90:
[95 93 93]

Student Grades:
Student 1: Average = 50.50, Grade = D
Student 2: Average = 59.75, Grade = D
Student 3: Average = 52.75, Grade = D
Student 4: Average = 44.75, Grade = F
Student 5: Average = 65.75, Grade = C
Student 6: Average = 70.00, Grade = B
Student 7: Average = 46.25, G